#ifndef JOI_GRAD_SHOPPING_CART_C_SHOPPING_CART_TEST_H
#define JOI_GRAD_SHOPPING_CART_C_SHOPPING_CART_TEST_H

void shopping_cart_test_should_calculate_price_with_no_discount(void);

void shopping_cart_test_should_calculate_loyalty_points_with_no_discount(void);

void shopping_cart_test_should_calculate_price_for_10_percent_discount(void);

void shopping_cart_test_should_calculate_loyalty_points_for_10_percent_discount(void);

void shopping_cart_test_should_calculate_price_for_15_percent_discount(void);

void shopping_cart_test_should_calculate_loyalty_points_for_15_percent_discount(void);

void shopping_cart_test_should_calculate_price_for_20_percent_discount(void);

void shopping_cart_test_should_calculate_loyalty_points_for_20_percent_discount(void);

void shopping_cart_test_should_calculate_price_for_buy_2_get_1(void);

void shopping_cart_test_should_calculate_loyalty_points_for_buy_2_get_1(void);

void shopping_cart_test_should_calculate_price_for_buy_2_get_1_with_two_products(void);

void shopping_cart_test_should_calculate_loyalty_points_for_buy_2_get_1_two_products(void);

void shopping_cart_test_should_calculate_price_for_buy_2_get_1_with_different_products(void);

void shopping_cart_test_should_calculate_loyalty_points_for_buy_2_get_1_different_products(void);

void shopping_cart_test_should_calculate_price_for_buy_2_get_1_with_5_same_products(void);

void shopping_cart_test_should_calculate_loyalty_points_for_buy_2_get_1_with_5_same_products(void);

void shopping_cart_test_should_calculate_price_for_buy_2_get_1_with_6_same_products(void);

void shopping_cart_test_should_calculate_loyalty_points_for_buy_2_get_1_with_6_same_products(void);

#endif //JOI_GRAD_SHOPPING_CART_C_SHOPPING_CART_TEST_H
